Feat/accepted user
GSM-MSG/GAUTH_BackEnd pull request #92
Opened 2023-02-28 07:52 UTC by KimTaeO

## 💡 개요
회원가입 수락된 유저 리스트
## 📃 작업내용
회원가입이 수락된 유저 리스트 기능 구현
## 🔀 변경사항

## 🙋‍♂️ 질문사항

## ⚗️ 사용법

## 🎸 기타

2023-02-28 07:56 UTC, baekteun requested changes

2023-02-28 07:56 UTC, baekteun commented on src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
> +    }
왜 Get인데 body가..?

2023-02-28 08:55 UTC, dolong2 commented on src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
> +    }
쿼리스트링으로 받는게 좋을듯

2023-02-28 10:00 UTC, KimTaeO commented on src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
> +    }
쿼리스트링으로 받도록 수정했습니다

2023-02-28 12:37 UTC, dolong2 approved these changes

2023-02-28 12:46 UTC, baekteun commented on src/main/kotlin/com/msg/gauth/domain/user/services/AcceptedUserService.kt
> +        return userRepository.findAll(spec)
수락된 유저만 가져오는건데 수락 여부 판단하는건 없는거같은데 정상 작동하나요?

2023-02-28 17:42 UTC, KimTaeO commented on src/main/kotlin/com/msg/gauth/domain/user/services/AcceptedUserService.kt
> +        return userRepository.findAll(spec)
https://github.com/GSM-MSG/GAUTH_BackEnd/pull/92/commits/2758651c163b9e925467eee0cc0a4a9c8d6a4526
학생인 것만 가져오려는 생각하다가 깜빡해버렸네요 추가했습니다

2023-03-05 07:13 UTC, baekteun approved these changes

2023-03-05 23:36 UTC, merged